### PR TITLE
Boost button

### PR DESCRIPTION
**Pull request by alenachao**
Very new to open source so please let me know if you have any feedback! One clarification I was wondering is what we want to return for the function.

### CODE REVIEW

**Comment by tkellogg** [comment]
ha, i love what you went with. do you mind if i merge it now? i just want to pull it down locally first.

**Comment by alenachao** [comment]
of course!

**Comment by tkellogg** [comment]
It doesn't quite work. See [my branch](https://github.com/tkellogg/fossil/tree/boost_button) for a couple small fixes, mainly around error handling. You might notice that your boosts probably didn't work (or maybe they did, just showed ups as your own toot, idk).

You have the URL wrong. You need this one: https://docs.joinmastodon.org/methods/statuses/#boost

**Comment by alenachao** [comment]
ok hopefully it works as intended now sorry about that!

**Comment by tkellogg** [comment]
Merged. Thanks so much for the contribution. See if you can do the like button too!

FYI, I added a cleanup commit, 5b6569319c04c72272c1cafda5cb6e3b9ce89f1b, mostly because i had an unrelated problem i was trying to troubleshoot. One note though — the `Toot.id` field is internal and doesn't correspond to toots on the mastodon server, so you have to use `Toot.toot_id` instead. Sorry for the confusion 😊

**Pull request merged**
